### ISSUE TITLE
Fix Deno import warning

### ISSUE THREAD

**Issue by shah** [cfjello/cxgraph#1]
@cfjello this is a great library, thanks for sharing it!

Please update to a new version and pin your dependency to eliminate this Deno warning:

```
Warning Implicitly using latest version (v1.0) for https://deno.land/x/hierarkey/mod.ts
```

Thanks!

**Comment by cfjello** [comment]
Done: now v1.3 Nice to hear that someone is using the library! Regard,Claus Fjelloe-Jensen  Sent from Mail for Windows 10 From: Shahid ShahSent: Sunday, July 25, 2021 10:26 PMTo: cfjello/cxgraphCc: Claus Fjellø-Jensen; MentionSubject: [cfjello/cxgraph] Fix Deno import warning ***@***.*** this is a great library, thanks for sharing it!Please update to a new version and pin your dependency to eliminate this Deno warning:Warning Implicitly using latest version (v1.0) for https://deno.land/x/hierarkey/mod.tsThanks!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by shah** [comment]
Great, thanks!
